version: "3"

services:
  today-db:
    image: postgres:12.2
    container_name: today-db
    restart: "always"
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - today_db:/var/lib/postgresql/data

volumes:
  today_db:
