version: "3"

services:
  rustappoint-db:
    image: postgres:12.2
    container_name: rustappoint-db
    restart: "always"
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - rustappoint_db:/var/lib/postgresql/data

volumes:
  rustappoint_db:
